# Generated by Django 2.2.7 on 2020-06-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask.Interest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask.UserLogin')),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask.Answer')),
                ('upvoted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask.UserLogin')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask.UserLogin')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answerd_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask.UserLogin'),
        ),
        migrations.AddField(
            model_name='answer',
            name='que_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask.Question'),
        ),
    ]
