# Generated by Django 2.2.7 on 2020-06-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ask', '0002_interest_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user_id',
        ),
    ]
