# Generated by Django 2.2.7 on 2020-06-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ask', '0003_remove_interest_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ask.Interest'),
            preserve_default=False,
        ),
    ]
